import { PERMISSIONS } from 'react-native-permissions';
export default {
  //Permissions ANDROID
  ANDROID_CAMERA: PERMISSIONS.ANDROID.CAMERA,
  ANDROID_READ_EXTERNAL_STORAGE: 'photo',
  //Permissions IOS
  IOS_CAMERA_PERMISSION: PERMISSIONS.IOS.CAMERA,
  IOS_PHOTO_LIBRARY: PERMISSIONS.IOS.PHOTO_LIBRARY,
  IOS_MEDIA_LIBRARY: PERMISSIONS.IOS.MEDIA_LIBRARY,
};
